# Generated by Django 2.2.4 on 2021-05-25 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='show',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default='2021-05-25'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='show',
            name='desc',
            field=models.TextField(default='Nice Show'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='show',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
