# Generated by Django 2.2.4 on 2021-05-22 19:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Model',
            new_name='Ninja',
        ),
    ]
