# Generated by Django 2.2.4 on 2021-05-26 12:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Car',
        ),
    ]
